# Default configuration file
# This file is intended as a user-facing manual.
# Modify the values below according to your dataset, model, and evaluation setup.

device: auto
# Options:
#   auto  : use cuda if available, else mps if available, else cpu
#   cpu   : force CPU
#   cuda  : force NVIDIA GPU
#   mps   : force Apple Silicon GPU

verbose: True

data:
  name: MS_COCO
  # Options:
  #   MS_COCO : Microsoft COCO dataset
  dataset_root: "/Users/rashid/data/DS/MS_COCO"
  image_dir: "/Users/rashid/data/DS/MS_COCO/val2017"
  annotation_file: "/Users/rashid/data/DS/MS_COCO/annotations/annotations_trainval2017/annotations/instances_val2017.json"

  masks_path: "/Users/rashid/data/PhD/datacloud_data/repos/XAI/ShapBPT-SAM/shap_bpt_sam/examples/data"
  mask_dir: "risultati_120"
  mask_dir_final: "120_refined_filled"

model:
  yolo_model_name: "yolo11s"
  # Options:
  #   yolo11s : YOLOv11s
  #   yolo26s : YOLOv26s

output:
  folder: "results"
  dir: /Users/rashid/data/PhD/datacloud_data/repos/XAI/ShapBPT-SAM/shap_bpt_sam/examples/
